### ISSUE TITLE
Tìm hiểu và tạo cơ sở dữ liệu

### ISSUE THREAD

**Issue by Trong1102** [Trong1102/CNPM#12]
Tạo cơ sở dữ liệu để lưu trữ và quản lý thông tin của đối tượng bao gồm các thuộc tính:
- Thông tin các nhân của từng đối tượng
- Điểm của sinh viên 
- Tình trạng các môn học của từng sinh viên

**Comment by quantienquanz** [comment]
Để tạo cơ sở dữ liệu cho việc quản lý thông tin của đối tượng, bạn có thể tạo các bảng chứa thông tin về nhân vật, điểm sinh viên và tình trạng môn học. Mỗi bảng có các trường tương ứng với thuộc tính yêu cầu. Ví dụ:

Bảng "Thông tin nhân vật":

ID: mã duy nhất cho mỗi nhân vật
Tên: tên của nhân vật
Tuổi: tuổi của nhân vật
Bảng "Điểm sinh viên":

ID: mã duy nhất cho mỗi sinh viên
ID_nhân_vật: mã nhân vật liên kết tới sinh viên
Điểm_trung_bình: điểm trung bình của sinh viên
Bảng "Tình trạng môn học":

ID: mã duy nhất cho mỗi tình trạng môn học
ID_sinh_viên: mã sinh viên liên kết tới tình trạng môn học
Môn_học: tên môn học
Tình_trạng: tình trạng của môn học (ví dụ: đã hoàn thành, đang học)
