### ISSUE TITLE
Thêm chức năng xuất hàng

### ISSUE THREAD

**Issue by Trong1102** [Trong1102/CNPM#14]
Bao gồm những thông tin sau của mặt hàng:
- Mã đơn xuất
- Mã sản phẩm 
- Số lượng xuất
- Tổng tiền
- Ghi chú
- Ngày xuất
- Người xuất

**Comment by Tuan23092002** [comment]
![image](https://user-images.githubusercontent.com/121219346/222323054-e02d4483-da96-4872-8864-68d884177383.png)

**Comment by Tuan23092002** [comment]
![image](https://user-images.githubusercontent.com/121219346/222323185-539bc7e8-6976-4233-92a1-59ef271acd3d.png)
