### ISSUE TITLE
Thêm chức năng xem hàng tồn kho

### ISSUE THREAD

**Issue by Trong1102** [Trong1102/CNPM#15]
Thông tin bao gồm:
- Tên sản phẩm
- Mã sản phẩm
- Số lượng tồn kho 
- Giá sản phẩm 
- Số lượng nhập
- Số lượng xuất
- Chi tiết về nhập, xuất

**Comment by Tuan23092002** [comment]
![image](https://user-images.githubusercontent.com/121219346/222322887-8e3a9969-c037-4690-ac7d-0364ca124470.png)

**Comment by Tuan23092002** [comment]
đã hoàn thành phần tồn kho
