### ISSUE TITLE
Thiết kế giao diện cho đối tượng Admin

### ISSUE THREAD

**Issue by Trong1102** [Trong1102/CNPM#9]
Bao gồm các chức năng:

- [x] - Đăng nhập 
- [x] - Quản lý người dùng
- [x] - Thống kê

**Comment by Trong1102** [comment]
https://github.com/Trong1102/CNPM/tree/main/CSS/style
https://github.com/Trong1102/CNPM/tree/main/HTML

**Comment by nguyenmaianh249** [comment]
Phần tiêu đề bạn ghi là thiết kế giao diện nhưng phần checklists thì bạn lại ghi các chức năng.
